export const IPC_CHANNELS = {
  IPC_EXAMPLE: 'IPC_EXAMPLE',
  CREATE_IFRAME_WINDOW: 'CREATE_IFRAME_WINDOW',
} as const;

export const JSB_EVENTS = {
  IFRAME_TO_ELECTRON: 'IFRAME_TO_ELECTRON',
  ELECTRON_TO_IFRAME: 'ELECTRON_TO_IFRAME',
} as const;
